# Generated by Django 4.0.5 on 2023-05-29 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_userinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='ipaddress',
            new_name='address',
        ),
    ]
